# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC002():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()

  def test_TC002(self):
    self.driver.get("https://fojin.tech/")
    self.driver.set_window_size(1552, 928)
    time.sleep(2)

    self.driver.find_element(By.LINK_TEXT, "Кейсы").click()
    time.sleep(3)

    self.vars["window_handles"] = self.driver.window_handles
    element = self.driver.find_element(By.CSS_SELECTOR, ".iteco_case__block__6L0LX")
    self.driver.execute_script("arguments[0].scrollIntoView(true);", element)
    time.sleep(1)

    self.driver.execute_script("arguments[0].click();", element)
    self.vars["win6239"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6239"])

