# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC007():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_tC007(self):
    self.driver.get("https://fojin.tech/")
    self.driver.set_window_size(1552, 928)
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Кейсы").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Награды").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Медиа").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Специалисты").click()
    time.sleep(2)

  
