# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC010():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()

  def test_tC010(self):
    self.driver.get("https://fojin.tech/")
    self.driver.set_window_size(1552, 928)
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Награды").click()
    time.sleep(3)
    self.vars["window_handles"] = self.driver.window_handles
    element = self.driver.find_element(By.CSS_SELECTOR,
                                       ".slider-group_slide_block__collapsed__c_tYs .slide:nth-child(1) svg")
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", element)
    time.sleep(1)
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click().perform()
    self.vars["win918"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.driver.window_handles[-1])
    time.sleep(2)
