# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC008():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_tC008(self):
    self.driver.get("https://fojin.tech/")
    self.driver.set_window_size(1552, 928)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR,
                             ".header_header__actions__submit__0EIOT > .Text_text-body1__kXpUJ").click()
    time.sleep(1)
    name_field = self.driver.find_element(By.ID, "name")
    name_field.clear()
    name_field.send_keys("Alex")
    time.sleep(0.5)
    contact_field = self.driver.find_element(By.ID, "contact")
    contact_field.clear()
    contact_field.send_keys("+79991234567")
    time.sleep(0.5)
    company_field = self.driver.find_element(By.ID, "company")
    company_field.clear()
    company_field.send_keys("Fojin")
    time.sleep(0.5)
    message_field = self.driver.find_element(By.CSS_SELECTOR, "textarea#company, #message, [name='message']")
    message_field.clear()
    message_field.send_keys("Хочу протестировать форму заявки")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".form_form__button__rXg0o").click()
    time.sleep(3)
  
